# ~/multi-container-Pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    # ports:
    # - containerPort: 80
  - name: busybox-container
    image: busybox:latest
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do echo 'Hello, Kubernetes!'; sleep 10; done"

