# ~/multi-container-Pod-with-host-path.yaml
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-with-host-path
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - mountPath: /var/config
      name: my-host-path-volume
  - name: busybox-container
    image: busybox:latest
    volumeMounts:
    - mountPath: /var/config
      name: my-host-path-volume
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"] # Prevents busybox from exiting after completion
  volumes:
  - name: my-host-path-volume
    hostPath:
      path: /tmp # The path on the worker node.
