apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-02-22T00:16:32Z"
  labels:
    run: nginxpod
  name: nginxpod
  namespace: default
  resourceVersion: "1912"
  selfLink: /api/v1/namespaces/default/pods/nginxpod
  uid: b3c8caa2-973c-4581-8a3b-7cc5f148b1a6
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginxpod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-s6zjm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-s6zjm
    secret:
      defaultMode: 420
      secretName: default-token-s6zjm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-02-22T00:16:32Z"
    message: '0/4 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master:
      }, that the pod didn''t tolerate, 3 node(s) had taint {node.kubernetes.io/not-ready:
      }, that the pod didn''t tolerate.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
