# ~/nginx-pod-with-secret-volume.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: mysecret-volume # Name of the volume
      mountPath: /etc/password-mounted-path
  volumes:
  - name: mysecret-volume
    secret:
      secretName: mypassword # Name of secret

