# ~/nginx-pod-with-secret-envfrom.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-with-secret-envfrom
  namespace: default
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    envFrom:
    - secretRef:
        name: mysecret # Name of the secret object
