# ~/persistent-volume-pd.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-pd
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: xxxx
    fsType: ext4

